version: '3.9'

services:
  nginx_main:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
  app1:
    build: .
    restart: always
    ports:
      - "8001:3000"
  app2:
    build: .
    restart: always
    ports:
      - "8002:3000"
  app3:
    build: .
    restart: always
    ports:
      - "8003:3000"



